install.packages("quantmod")
install.packages("tinytex")
install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("knitr")
install.packages("rmarkdown")
