install.packages("dplyr")
install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("rstan")
